"""empty message

Revision ID: 064cb17a9ef8
Revises: 6031303b447a
Create Date: 2022-06-20 00:37:30.326349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064cb17a9ef8'
down_revision = '6031303b447a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='genre_pkey')
    )
    # ### end Alembic commands ###
