"""empty message

Revision ID: 280260467572
Revises: 25052ba9d1c8
Create Date: 2022-06-19 23:11:29.256579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280260467572'
down_revision = '25052ba9d1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('overview', sa.Text(), nullable=True))
    op.add_column('movie', sa.Column('homepage', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('vote_average', sa.Float(), nullable=True))
    op.add_column('movie', sa.Column('runtime', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('poster_path', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('backdrop_path', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('genre_name', sa.String(), nullable=True))
    op.drop_column('movie', 'rating')
    op.drop_column('movie', 'desc')
    op.drop_column('movie', 'img')
    op.drop_column('movie', 'run_time')
    op.drop_column('movie', 'trailer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('trailer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('run_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('desc', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('movie', 'genre_name')
    op.drop_column('movie', 'backdrop_path')
    op.drop_column('movie', 'poster_path')
    op.drop_column('movie', 'runtime')
    op.drop_column('movie', 'vote_average')
    op.drop_column('movie', 'homepage')
    op.drop_column('movie', 'overview')
    op.drop_column('movie', 'tmdb_id')
    # ### end Alembic commands ###
