"""empty message

Revision ID: 6031303b447a
Revises: 280260467572
Create Date: 2022-06-20 00:36:15.290478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6031303b447a'
down_revision = '280260467572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_genre_id_fkey', 'movie', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('movie_genre_id_fkey', 'movie', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###
